# Generated by Django 2.0.7 on 2019-06-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_waters', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('finished_time', models.IntegerField(default=0)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet')),
            ],
        ),
    ]
