# Generated by Django 2.0.7 on 2019-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_drinkactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkactivity',
            name='current_waters',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
