# Generated by Django 2.0.7 on 2019-06-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_auto_20190630_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkactivity',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
