# Generated by Django 2.0.7 on 2018-12-23 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasUser',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')])),
                ('password', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=18, unique=True)),
                ('gender', models.IntegerField(default=1)),
                ('avatar', models.IntegerField(default=-1)),
                ('money', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
