# Generated by Django 2.0.7 on 2018-11-08 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')])),
                ('password', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=18, unique=True)),
                ('gender', models.IntegerField(default=1)),
                ('avatar', models.IntegerField(default=-1)),
                ('money', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
