# Generated by Django 2.0.7 on 2018-08-02 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')])),
                ('password', models.CharField(max_length=32)),
                ('nick_name', models.CharField(default='', max_length=15)),
                ('slogan', models.CharField(default='', max_length=50)),
                ('work_mes', models.CharField(default='', max_length=20)),
                ('interest_mes', models.CharField(default='', max_length=20)),
                ('travel_mes', models.CharField(default='', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
