# Generated by Django 2.0.7 on 2018-07-23 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masuser',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masuser',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
