# Generated by Django 2.0.7 on 2018-10-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masuser',
            name='interest_mes',
        ),
        migrations.RemoveField(
            model_name='masuser',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='masuser',
            name='travel_mes',
        ),
        migrations.RemoveField(
            model_name='masuser',
            name='work_mes',
        ),
        migrations.AddField(
            model_name='masuser',
            name='gender',
            field=models.IntegerField(default=1),
        ),
    ]
