# Generated by Django 2.0.7 on 2018-07-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180723_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='masuser',
            name='nick_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
