# Generated by Django 2.0.7 on 2018-10-05 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_masuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masuser',
            name='nick_name',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='masuser',
            name='username',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
    ]
