# Generated by Django 2.0.7 on 2018-10-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181005_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masuser',
            name='nick_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
