# Generated by Django 2.0.7 on 2018-10-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181005_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='masuser',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
