# Generated by Django 2.0.7 on 2019-02-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0004_remove_pet_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_consume', models.IntegerField(default=100)),
                ('water_residue', models.IntegerField(default=0)),
                ('time_residue', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetDrinkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_water', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('pet_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet')),
            ],
        ),
    ]
