# Generated by Django 2.0.7 on 2019-02-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_drink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petdrink',
            name='id',
        ),
        migrations.AlterField(
            model_name='petdrink',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pet.Pet'),
        ),
    ]
