# Generated by Django 2.0.7 on 2019-02-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_drink', '0002_auto_20190225_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petdrink',
            name='time_residue',
        ),
    ]
