# Generated by Django 2.0.7 on 2019-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_dogplay_dogplaytarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogplay',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='dogplay',
            name='kals_today',
        ),
        migrations.AddField(
            model_name='dogplay',
            name='durations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dogplay',
            name='kals',
            field=models.IntegerField(default=0),
        ),
    ]
