# Generated by Django 2.0.7 on 2018-12-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('uid', models.CharField(max_length=10, unique=True)),
                ('relationship_code', models.IntegerField(default=-1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
