# Generated by Django 2.0.7 on 2019-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrelationship',
            name='uid',
            field=models.CharField(max_length=10),
        ),
    ]
