# Generated by Django 2.0.7 on 2018-08-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
