# Generated by Django 2.0.7 on 2018-08-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_avatar', '0002_auto_20180804_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar'),
        ),
    ]
