# Generated by Django 2.0.7 on 2018-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_avatar', '0003_auto_20180804_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='', upload_to='userAvatar'),
        ),
    ]
