# Generated by Django 2.0.7 on 2019-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('own_id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('own_type', models.IntegerField(default=0)),
                ('avatar_key', models.CharField(max_length=50)),
            ],
        ),
    ]
