# Generated by Django 2.0.7 on 2019-07-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='masuser',
        ),
        migrations.AddField(
            model_name='blog',
            name='imgs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
            preserve_default=False,
        ),
    ]
