# Generated by Django 2.0.7 on 2018-09-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
