# Generated by Django 2.0.7 on 2019-06-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userA', to='user.MasUser')),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userB', to='user.MasUser')),
            ],
        ),
    ]
