# Generated by Django 2.0.7 on 2019-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed_type',
            field=models.CharField(default='威玛猎犬', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='food_weight',
            field=models.IntegerField(default=0),
        ),
    ]
