# Generated by Django 2.0.7 on 2019-01-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20190106_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=5000),
        ),
    ]
