# Generated by Django 2.0.7 on 2019-01-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20190107_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='avatar',
        ),
    ]
