# Generated by Django 2.0.7 on 2018-11-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtualPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=18, unique=True)),
                ('gender', models.IntegerField()),
                ('breed', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('pet_id', models.CharField(max_length=10, unique=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MasUser')),
            ],
        ),
    ]
