# Generated by Django 2.0.7 on 2018-10-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualpet',
            old_name='avtar',
            new_name='breed',
        ),
    ]
