# Generated by Django 2.0.7 on 2019-07-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20190701_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkscore',
            name='score',
            field=models.DecimalField(decimal_places=1, default=8.0, max_digits=3),
        ),
    ]
